CREATE TABLE BEATMAPSET_COVERS
(
    BEATMAPSET_ID           BIGINT                                    NOT NULL PRIMARY KEY,
    COVER                   VARCHAR(255)                              NOT NULL,
    COVER2X                 VARCHAR(255)                              NOT NULL,
    CARD                    VARCHAR(255)                              NOT NULL,
    CARD2X                  VARCHAR(255)                              NOT NULL,
    LIST                    VARCHAR(255)                              NOT NULL,
    LIST2X                  VARCHAR(255)                              NOT NULL,
    SLIM_COVER              VARCHAR(255)                              NOT NULL,
    SLIM_COVER2X            VARCHAR(255)                              NOT NULL,
    SYSTEM_CREATE_TIMESTAMP TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    SYSTEM_UPDATE_TIMESTAMP TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL ON UPDATE CURRENT_TIMESTAMP(6)
) COLLATE = UTF8MB3_UNICODE_CI;

CREATE TABLE BANCHO_USER
(
    ID                      BIGINT                                    NOT NULL PRIMARY KEY,
    AVATAR_URL              VARCHAR(255)                              NOT NULL,
    COUNTRY_CODE            VARCHAR(255)                              NOT NULL,
    DEFAULT_GROUP           VARCHAR(255)                              NULL,
    IS_ACTIVE               BOOL                                      NOT NULL,
    IS_BOT                  BOOL                                      NOT NULL,
    IS_DELETED              BOOL                                      NOT NULL,
    IS_ONLINE               BOOL                                      NOT NULL,
    IS_SUPPORTER            BOOL                                      NOT NULL,
    LAST_VISIT              TIMESTAMP(6)                              NOT NULL,
    PM_FRIENDS_ONLY         BOOL                                      NOT NULL,
    PROFILE_COLOUR          VARCHAR(255)                              NULL,
    USERNAME                VARCHAR(255)                              NOT NULL,
    SYSTEM_CREATE_TIMESTAMP TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    SYSTEM_UPDATE_TIMESTAMP TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL ON UPDATE CURRENT_TIMESTAMP(6)
) COLLATE = UTF8MB3_UNICODE_CI;

CREATE TABLE BEATMAP
(
    ID                      INT                                       NOT NULL PRIMARY KEY,
    BEATMAPSET_ID           INT                                       NOT NULL,
    DIFFICULTY_RATING       DOUBLE                                    NOT NULL,
    MODE                    VARCHAR(255)                              NOT NULL,
    STATUS                  VARCHAR(255)                              NOT NULL,
    TOTAL_LENGTH            INT                                       NOT NULL,
    USER_ID                 INT                                       NOT NULL,
    VERSION                 VARCHAR(255)                              NOT NULL,
    -- ======================================================================================================
    ACCURACY                DOUBLE                                    NULL,
    AR                      DOUBLE                                    NULL,
    BPM                     DOUBLE                                    NULL,
    CONVERTED               BOOL                                      NULL,
    COUNT_CIRCLES           INT                                       NULL,
    COUNT_SLIDERS           INT                                       NULL,
    COUNT_SPINNERS          INT                                       NULL,
    CS                      DOUBLE                                    NULL,
    DELETED_AT              TIMESTAMP(6)                              NULL,
    DRAIN                   DOUBLE                                    NULL,
    HIT_LENGTH              INT                                       NULL,
    IS_SCOREABLE            BOOL                                      NULL,
    LAST_UPDATED            TIMESTAMP(6)                              NULL,
    MODE_INT                INT                                       NULL,
    PASSCOUNT               INT                                       NULL,
    PLAYCOUNT               INT                                       NULL,
    RANKED                  INT                                       NULL,
    URL                     VARCHAR(2048)                             NULL,
    CHECKSUM                VARCHAR(255)                              NULL,
    MAX_COMBO               INT                                       NULL,
    FAILTIMES_FAIL          LONGTEXT                                  NULL,
    FAILTIMES_EXIT          LONGTEXT                                  NULL,
    SYSTEM_CREATE_TIMESTAMP TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NULL,
    SYSTEM_UPDATE_TIMESTAMP TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NULL ON UPDATE CURRENT_TIMESTAMP(6)
) COLLATE = UTF8MB3_UNICODE_CI;

CREATE TABLE BEATMAPSET
(
    ID                                INT                                       NOT NULL PRIMARY KEY,
    ARTIST                            VARCHAR(255)                              NOT NULL,
    ARTIST_UNICODE                    VARCHAR(255)                              NOT NULL,
    CREATOR                           VARCHAR(255)                              NOT NULL,
    FAVOURITE_COUNT                   INT                                       NOT NULL,
    HYPE_CURRENT                      INT                                       NULL,
    HYPE_REQUIRED                     INT                                       NULL,
    NSFW                              BOOL                                      NOT NULL,
    SET_OFFSET                        INT                                       NOT NULL,
    PLAY_COUNT                        INT                                       NOT NULL,
    PREVIEW_URL                       VARCHAR(255)                              NOT NULL,
    SOURCE                            VARCHAR(255)                              NOT NULL,
    SPOTLIGHT                         BOOL                                      NOT NULL,
    STATUS                            VARCHAR(255)                              NOT NULL,
    TITLE                             VARCHAR(255)                              NOT NULL,
    TITLE_UNICODE                     VARCHAR(255)                              NOT NULL,
    TRACK_ID                          INT                                       NULL,
    USER_ID                           INT                                       NOT NULL,
    VIDEO                             BOOL                                      NOT NULL,
    -- ======================================================================================================
    BPM                               DOUBLE                                    NULL,
    CAN_BE_HYPED                      BOOL                                      NULL,
    DELETED_AT                        TIMESTAMP(6)                              NULL,
    DISCUSSION_ENABLED                BOOL                                      NULL,
    DISCUSSION_LOCKED                 BOOL                                      NULL,
    IS_SCOREABLE                      BOOL                                      NULL,
    LAST_UPDATED                      TIMESTAMP(6)                              NULL,
    LEGACY_THREAD_URL                 VARCHAR(2048)                             NULL,
    NOMINATIONS_CURRENT               INT                                       NULL,
    NOMINATIONS_REQUIRED              INT                                       NULL,
    RANKED                            INT                                       NULL,
    RANKED_DATE                       TIMESTAMP(6)                              NULL,
    STORYBOARD                        BOOL                                      NULL,
    SUBMITTED_DATE                    TIMESTAMP(6)                              NULL,
    TAGS                              TEXT                                      NULL,
    AVAILABILITY_DOWNLOAD_DISABLED    BOOL                                      NULL,
    AVAILABILITY_MORE_INFORMATION     VARCHAR(2048)                             NULL,
    HAS_FAVOURITED                    BOOL                                      NULL,
    PACK_TAGS                         LONGTEXT                                  NULL,
    CURRENT_NOMINATIONS_BEATMAPSET_ID INT                                       NULL,
    CURRENT_NOMINATIONS_RESET         BOOL                                      NULL,
    CURRENT_NOMINATIONS_RULESETS      LONGTEXT                                  NULL,
    CURRENT_NOMINATIONS_USER_ID       INT                                       NULL,
    DESCRIPTION_BBCODE                LONGTEXT                                  NULL,
    DESCRIPTION_DESCRIPTION           LONGTEXT                                  NULL,
    GENRE_ID                          INT                                       NULL,
    GENRE_NAME                        VARCHAR(255)                              NULL,
    LANGUAGE_ID                       INT                                       NULL,
    LANGUAGE_NAME                     VARCHAR(255)                              NULL,
    RATINGS                           LONGTEXT                                  NULL,
    SYSTEM_CREATE_TIMESTAMP           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    SYSTEM_UPDATE_TIMESTAMP           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL ON UPDATE CURRENT_TIMESTAMP(6)
) COLLATE = UTF8MB3_UNICODE_CI;