basePath: /
host: xiiov.com
info:
  contact:
    email: thftgr@gmail.com
    name: API Support
  description: thftgr's fast cached osu beatmap mirror.
  license:
    name: GNU General Public License v3.0
    url: https://github.com/thftgr/osuFastCashedBeatmapMirror/blob/master/LICENSE
  termsOfService: https://github.com/thftgr/osuFastCashedBeatmapMirror
  title: Swagger Example API
  version: "1.0"
paths:
  /d/{map_set_id}:
    get:
      description: 비트맵셋 다운로드.
      parameters:
      - description: download without video
        in: query
        name: nv
        type: boolean
      - description: download without video
        in: query
        name: noVideo
        type: boolean
      - description: beatmap set id
        in: path
        name: map_set_id
        required: true
        type: integer
      responses:
        "200":
          description: ""
        "500":
          description: InternalServerError
          schema:
            type: body
      summary: .
  /health:
    get:
      description: 서버 상태 체크.
      responses:
        "200":
          description: ""
      summary: Host health checker.
schemes:
- http
- https
swagger: "2.0"
