basePath: /
host: xiiov.com
info:
  contact:
    email: thftgr@gmail.com
    name: API Support
  description: thftgr's fast cached osu beatmap mirror.
  license:
    name: GNU General Public License v3.0
    url: https://github.com/thftgr/osuFastCashedBeatmapMirror/blob/master/LICENSE
  termsOfService: https://github.com/thftgr/osuFastCashedBeatmapMirror
  title: Swagger Example API
  version: "1.0"
paths:
  /health:
    get:
      description: 서버 상태 체크.
      responses:
        "200":
          description: ""
      summary: Host health checker.
swagger: "2.0"
