name: Docker Image CI

on:
  push:
    branches: [ "master","release" ]
  pull_request:
    branches: [ "master","release" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nerinyan-apiv2
  REPOSITORY_OWNER: nerinyan

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
        
      - name: Golang with cache
        uses: magnetikonline/action-golang-cache@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      
#       - name: Cache Docker layers
#         uses: actions/cache@v2
#         with:
#           path: /tmp/.build-cache
#           key: ${{ runner.os }}-buildx-${{ github.sha }}
#           restore-keys: |
#             ${{ runner.os }}-buildx-
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:latest
#           cache-from: type=local,src=/tmp/.build-cache
#           cache-to: type=local,dest=/tmp/.build-cache
          target: build
