name: Docker Image CI

on:
  push:
    branches: [ "master","release" ]
  pull_request:
    branches: [ "master","release" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nerinyan-apiv2
  REPOSITORY_OWNER: nerinyan

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
        
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.3'
          
      - name: Install dependencies
        run: go mod download
        
      - name: build-amd64
        run: CGO_ENABLED=0; GOARCH=amd64; GOOS=linux; go build -ldflags="-w -s" -o /app-${GOOS}-${GOARCH}
      - name: build-arm64
        run: CGO_ENABLED=0; GOARCH=arm64; GOOS=linux; go build -ldflags="-w -s" -o /app-${GOOS}-${GOARCH}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile.github
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:latest
